name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Test
        run: swift test -Xswiftc -warnings-as-errors
      - name: Build
        run: swift build --configuration release
